- name: Add ppa for java8
  apt_repository: repo='ppa:webupd8team/java'

- name: Autoaccept license for Java
  action: shell echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install java8
  apt: name=oracle-java8-installer update_cache=yes
